---
- name: Copy file
  ansible.builtin.copy:
    src: test.txt
    dest: /root/test.txt
    owner: root
    group: root
    mode: 0600

- name: Install apache httpd (state=present is optional)
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Ensure nginx is not here
  ansible.builtin.apt:
    name: nginx
    state: absent